image: ksfmedia/diskho:lts-18.13

variables:
  DOCKER_DRIVER: overlay2
  GIT_SUBMODULE_STRATEGY: recursive
  CI_SCRIPTS: "${CI_PROJECT_DIR}/infra/ci-scripts"
  YARN_CACHE: "${CI_PROJECT_DIR}/.yarn-cache"

.mosaico-ci-variables: &mosaico-ci-vars
  SERVICE_NAME: mosaico
.app-article-ci-variables: &app-article-ci-vars
  SERVICE_NAME: app-article-server

before_script:
  - eval `./infra/ci-scripts/prepare_stage_envvars.py ${CI_ENVIRONMENT_SLUG}`

# You may also want a lint stage before the build
# and you might want to remove the update-clients job
stages:
#  - test
  - build
  - docker
  - deploy

# Build template
.build-app:
  stage: build
  environment: staging/$SERVICE_NAME
  only:
    - master
  cache:
    key: "affresco-yarn-cache"
    paths:
      - $YARN_CACHE
  artifacts:
    paths:
      - artifacts/
    when: always
    expire_in: 7 days
  script:
    - mkdir -p artifacts/staging
    - yarn install --pure-lockfile --cache-folder=$YARN_CACHE
    # build apps with staging vars
    - yarn --cwd apps/$SERVICE_NAME/ run build
    - cp -R apps/$SERVICE_NAME artifacts/staging/$SERVICE_NAME
    # rebuild with production vars
    - eval `./infra/ci-scripts/prepare_stage_envvars.py production`
    - mkdir -p artifacts/production
    - yarn --cwd apps/$SERVICE_NAME/ run build
    - cp -R apps/$SERVICE_NAME artifacts/production/$SERVICE_NAME

# Docker build template
.build-docker:
  stage: docker
  environment: staging/$SERVICE_NAME
  only:
    - master
  script:
    # docker build & push staging
    - cd artifacts/staging/$SERVICE_NAME
    - $CI_SCRIPTS/docker-build.sh
    - $CI_SCRIPTS/auth-gcloud.sh
    - $CI_SCRIPTS/docker-push.sh
    # docker buld & push production
    - cd artifacts/produciton/$SERVICE_NAME
    - $CI_SCRIPTS/docker-build.sh
    - KSF_ENV_TEXT=production GOOGLE_CREDENTIALS=$PRODUCTION_GOOGLE_CREDENTIALS $CI_SCRIPTS/auth-gcloud.sh
    - KSF_ENV_TEXT=production $CI_SCRIPTS/docker-push.sh

# Deploy template
.deploy:
  stage: deploy
  environment: staging/$SERVICE_NAME
  only:
    - master
  script:
    - ./infra/ci-scripts/auth-gcloud.sh
    - ./infra/ci-scripts/kubernetes-deployment.sh

# Build apps
mosaico-build:
  extends: .build-app
  variables: *mosaico-ci-vars

app-article-build:
  extends: .build-app
  variables: *app-article-ci-vars

# Build docker images
mosaico-docker-build:
  extends: .build-docker
  needs: 
    - mosaico-build
  variables: *mosaico-ci-vars

app-article-docker-build:
  extends: .build-docker
  needs: 
    - app-article-build
  variables: *app-article-ci-vars

# Deploy Staging
deploy-mosaico-staging:
  extends: .deploy
  needs: 
    - mosaico-docker-build
  variables: *mosaico-ci-vars

deploy-app-article-staging:
  extends: .deploy
  needs: 
    - app-article-docker-build
  variables: *app-article-ci-vars

# Deploy production
deploy-mosaico-production:
  extends: .deploy
  environment: production/$SERVICE_NAME
  when: manual
  variables: *mosaico-ci-vars

deploy-app-article-production:
  extends: .deploy
  environment: production/$SERVICE_NAME
  when: manual
  variables: *app-article-ci-vars
