name: mitt-konto
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'
    - run: yarn install
    - name: Run deploy script
      run: ruby deploy.rb mitt-konto
    - id: upload-files
      uses: GoogleCloudPlatform/github-actions/upload-cloud-storage@master
      with:
        path: apps/mitt-konto/dist
        destination: mitt-konto-poc-bucket
        credentials: ${{ secrets.GCS_SA }}
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT }}
        service_account_key: ${{ secrets.GCS_SA }}
        export_default_credentials: true
    - name: Invalidate CDN cache
      run: gcloud compute url-maps invalidate-cdn-cache mitt-konto-poc-lb --path "/*"
