name: mitt-konto
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v10
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'
    - run: yarn install
    - name: Run deploy script
      run: ruby deploy.rb mitt-konto
    - id: upload-files
      uses: GoogleCloudPlatform/github-actions/upload-cloud-storage@master
      with:
        path: apps/mitt-konto/dist
        destination: mitt-konto-poc-bucket
        credentials: ${{ secrets.GCS_SA }}
