jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: "actions/checkout@v2"
      - name: Setup node and yarn
        uses: "actions/setup-node@v1"
        with:
          node-version: '12'
      - name: Setup ruby
        uses: "actions/setup-ruby@v1"
        with:
          ruby-version: '2.6'
      - uses: "cachix/install-nix-action@v12"
        with:
          nix_path: nixpkgs=channel:nixos-20.09
      - name: Setup Cloud SDK
        uses: "google-github-actions/setup-gcloud@master"
        with:
          export_default_credentials: 'true'
          project_id: "${{ secrets.GCP_STAGING_PROJECT_ID }}"
          service_account_key: "${{ secrets.GCP_STAGING_AE_KEY }}"
      - name: Setup global build cache
        uses: "actions/cache@v2"
        with:
          key: "${{ runner.os }}-build-${{ hashFiles('yarn.lock')}}"
          path: |2
              **/node_modules
              **/.yarn-cache
              **/.cache
              ~/.npm
              ~/.cache/spago
              apps/elections/dist
              !build
              !build/*
              !build/**
      - run: |2
            yarn install --pure-lockfile --cache-folder=.yarn-cache
            mkdir -p build
      - name: Check CI script has been generated from Dhall
        run: |2
            make
            git diff --exit-code
      - name: Keep only 10 latest versions of App article server
        run: |2
            versions=$(gcloud app versions list \
              --service app-article-server \
              --sort-by '~VERSION.ID' \
              --filter 'traffic_split = 0.0' \
              --format 'value(VERSION.ID)' | sed 1,5d)
            for version in $versions; do
              gcloud app versions delete '$version' \
                --service app-article-server \
            done
      - name: Keep only 10 latest versions of Mosaico server
        run: |2
            versions=$(gcloud app versions list \
              --service mosaico-server \
              --sort-by '~VERSION.ID' \
              --filter 'traffic_split = 0.0' \
              --format 'value(VERSION.ID)' | sed 1,5d)
            for version in $versions; do
              gcloud app versions delete '$version' \
                --service mosaico-server \
            done
name: previews
on:
  pull_request:
    branches:
      - master
