name: previews

on:
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      preview_url: https://deploy-previews.ksfmedia.fi/${{ github.sha }}
    steps:
    # Setup steps
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Setup node and yarn
      uses: actions/setup-node@v1
      with:
        node-version: '12'
    - name: Setup ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'
    - run: yarn install

    # Builds
    - name: Build mitt-konto
      run: |
        ruby deploy.rb mitt-konto
        mv apps/mitt-konto/dist build-mitt-konto
    - name: Build vetrina-staging
      env:
        NODE_ENV: development
        SENTRY_DSN: https://6479d7c55fbd4e0db7d9ac755083865f@sentry.io/3718842
      run: |
        yarn --cwd './apps/vetrina-staging/' run build
        mv apps/vetrina-staging/dist build-vetrina-staging
    - name: Build ksf-elections-eu
      env:
        ELECTION_BACKEND_URL: https://elections-eu.api.ksfmedia.fi/v1
        ELECTION_TYPE: EU
      run: |
        ruby deploy.rb elections
        mv apps/elections/dist build-elections-eu
    - name: Build ksf-elections
      env:
        ELECTION_BACKEND_URL: https://election.api.ksfmedia.fi/v1
        ELECTION_TYPE: PARLIAMENT
      run: |
        ruby deploy.rb elections
        mv apps/elections/dist build-elections
    - name: Build app-article
      run: |
        ruby deploy.rb app-article
        mv apps/app-article/dist build-app-article
    - name: Build prenumerera
      run: |
        ruby deploy.rb prenumerera
        mv apps/prenumerera/dist build-prenumerera
    - name: Build affresco-scripts
      run: |
        ruby -e 'Dir.glob("scripts/**/*.js").each { |f| `uglifyjs #{f} -o #{f.gsub(/js\z/, "min.js")}` }'
    - name: Build duellen
      run: |
        ruby deploy.rb duellen
        mv apps/duellen/dist build-duellen
    - name: Build ksf-podcast-vn
      env:
        PODCAST_IDS: 694513583,705599305,630339678,542583531
      run: |
        yarn --cwd './apps/podcasts/' run build
        mv apps/podcasts/dist build-podcasts-vn
    - name: Build ksf-podcast
      env:
        PODCAST_IDS: 806886790
      run: |
        yarn --cwd './apps/podcasts/' run build
        mv apps/podcasts/dist build-podcasts

    # Upload all built artifacts to the GCP bucket
    - name: Upload mitt-konto
      uses: GoogleCloudPlatform/github-actions/upload-cloud-storage@master
      with:
        path: build-mitt-konto
        destination: mitt-konto-poc-bucket
        credentials: ${{ secrets.GCS_SA }}
    - name: Upload vetrina-staging
      uses: GoogleCloudPlatform/github-actions/upload-cloud-storage@master
      with:
        path: build-vetrina-staging
        destination: mitt-konto-poc-bucket
        credentials: ${{ secrets.GCS_SA }}
    - name: Upload ksf-elections-eu
      uses: GoogleCloudPlatform/github-actions/upload-cloud-storage@master
      with:
        path: build-elections-eu
        destination: mitt-konto-poc-bucket
        credentials: ${{ secrets.GCS_SA }}
    - name: Upload ksf-elections
      uses: GoogleCloudPlatform/github-actions/upload-cloud-storage@master
      with:
        path: build-elections
        destination: mitt-konto-poc-bucket
        credentials: ${{ secrets.GCS_SA }}
    - name: Upload app-article
      uses: GoogleCloudPlatform/github-actions/upload-cloud-storage@master
      with:
        path: build-app-article
        destination: mitt-konto-poc-bucket
        credentials: ${{ secrets.GCS_SA }}
    - name: Upload prenumerera
      uses: GoogleCloudPlatform/github-actions/upload-cloud-storage@master
      with:
        path: build-prenumerera
        destination: mitt-konto-poc-bucket
        credentials: ${{ secrets.GCS_SA }}
    - name: Upload affresco-scripts
      uses: GoogleCloudPlatform/github-actions/upload-cloud-storage@master
      with:
        path: scripts
        destination: mitt-konto-poc-bucket
        credentials: ${{ secrets.GCS_SA }}
    - name: Upload duellen
      uses: GoogleCloudPlatform/github-actions/upload-cloud-storage@master
      with:
        path: build-duellen
        destination: mitt-konto-poc-bucket
        credentials: ${{ secrets.GCS_SA }}
    - name: Upload ksf-podcasts-vn
      uses: GoogleCloudPlatform/github-actions/upload-cloud-storage@master
      with:
        path: build-podcasts-vn
        destination: mitt-konto-poc-bucket
        credentials: ${{ secrets.GCS_SA }}
    - name: Upload ksf-podcasts
      uses: GoogleCloudPlatform/github-actions/upload-cloud-storage@master
      with:
        path: build-podcasts
        destination: mitt-konto-poc-bucket
        credentials: ${{ secrets.GCS_SA }}

    # Post the preview links on the thread
    - name: Post preview links
      uses: unsplash/comment-on-pr@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        msg: |
          Deploy previews:
          - __Mitt Konto__: ${{ env.preview_url }}/mitt-konto
        check_for_duplicate_msg: true
